lexicon = {
            'Capricornus': 'Козерог',
            'Gemini': 'Близнецы',
            'Libra': 'Весы',
            'Aquarius': 'Водолей',
            'Virgo': 'Дева',
            'Leo': 'Лев',
            'Aries': 'Овен',
            'Andromeda': 'Андромеда',
            'Ursa Major': 'Большая Медведица',
            'Canis Major': 'Большой Пес',
            'Auriga': 'Возничий',
            'Lupus': 'Волк',
            'Bootes': 'Волопас',
            'Coma Berenices': 'Волосы Вероники',
            'Hercules': 'Геркулес',
            'Hydra': 'Гидра',
            'Columba': 'Голубь',
            'Canes Venatici': 'Гончие Псы',
            'Delphinus': 'Дельфин',
            'Draco Dra': 'Дракон',
            'Monoceros': 'Единорог',
            'Ara': 'Жертвенник',
            'Pictor': 'Живописец',
            'Camelopardalis': 'Жираф',
            'Grus': 'Журавль',
            'Lepus': 'Заяц', 
            'Ophiuchus': 'Змееносец', 
            'Serpens': 'Змея',
            'Dorado': 'Золотая Рыба',
            'Indus': 'Индеец',
            'Cassiopeia': 'Кассиопея',
            'Carina': 'Киль',
            'Cetus': 'Кит',
            'Pyxis': 'Компас',
            'Puppis': 'Корма',
            'Cygnus': 'Лебедь',
            'Volans': 'Летучая Рыба',
            'Lyra': 'Лира',
            'Vulpecula': 'Лисичка',
            'Ursa Minor': 'Малая Медведица',
            'Equuleus': 'Малый Конь',
            'Leo Minor': 'Малый Лев',
            'Canis Minor': 'Малый Пес',
            'Microscopium': 'Микроскоп',
            'Musca': 'Муха',
            'Antlia': 'Насос',
            'Norma': 'Наугольник',
            'Octans': 'Октант',
            'Aquila': 'Орел',
            'Orion': 'Орион',
            'Pavo': 'Павлин',
            'Vela': 'Паруса',
            'Pegasus': 'Пегас',
            'Perseus': 'Персей',
            'Fornax': 'Печь',
            'Apus': 'Райская Птица',
            'Cancer': 'Рак',
            'Caelum': 'Резец',
            'Pisces': 'Рыбы',            
            'Lynx': 'Рысь',
            'Corona Borealis': 'Северная Корона',
            'Sextans': 'Секстант',
            'Reticulum': 'Сетка',
            'Scorpius': 'Скорпион',
            'Sculptor': 'Скульптор',
            'Mensa': 'Столовая Гора',
            'Sagitta': 'Стрела',
            'Sagittarius': 'Стрелец',
            'Telescopium': 'Телескоп',
            'Taurus': 'Телец',
            'Triangulum': 'Треугольник',
            'Tucana': 'Тукан',
            'Phoenix': 'Феникс',
            'Chamaeleon': 'Хамелеон',
            'Centaurus': 'Центавр',
            'Cepheus': 'Цефей',
            'Circinus': 'Циркуль',
            'Horologium': 'Часы',
            'Crater': 'Чаша',
            'Scutum': 'Щит',
            'Eridanus': 'Эридан',
            'Hydrus': 'Южная Гидра',
            'Corona Australis': 'Южная Корона',
            'Piscis Austrinus': 'Южная Рыба',
            'Crux': 'Южный Крест',
            'Triangulum Australe': 'Южный Треугольник',
            'Lacerta': 'Ящерица',
            'Argo': 'Корабль Арго'
            }