lexicon = {
            'Capricornus': 'Козерог',
            'Gemini': 'Близнецы',
            'Libra': 'Весы',
            'Aquarius': 'Водолей',
            'Virgo': 'Дева',
            'Leo': 'Лев',
            'Aries': 'Овен',
            'Andromeda': 'Андромеда',
            'Ursa Major': 'Большая Медведица',
            'Canis Major': 'Большой Пес',
            'Auriga': 'Возничий',
            'Lupus': 'Волк',
            'Bootes': 'Волопас',
            'Coma Berenices': 'Волосы Вероники',
            'Hercules': 'Геркулес',
            'Hydra': 'Гидра',
            'Columba': 'Голубь',
            'Canes Venatici': 'Гончие Псы',
            'Delphinus': 'Дельфин'
            }